// <auto-generated />
namespace aspnet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class moviecontroller_securityupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moviecontroller_securityupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241656564_movie-controller_security-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
